# Generated by Django 5.0.3 on 2024-05-18 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('img', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('place', models.CharField(max_length=100)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
